"""empty message

Revision ID: 0612d1e43ae6
Revises: 8a304588c6c5
Create Date: 2018-02-10 10:24:32.794333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0612d1e43ae6'
down_revision = '8a304588c6c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('tags', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('question', 'tags')
    # ### end Alembic commands ###
