"""empty message

Revision ID: 8a304588c6c5
Revises: f6c57b555bf6
Create Date: 2018-01-09 11:20:00.040105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a304588c6c5'
down_revision = 'f6c57b555bf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moviename', sa.String(length=50), nullable=False),
    sa.Column('directer', sa.String(length=50), nullable=False),
    sa.Column('star', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('answer', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'create_time')
    op.drop_table('movie')
    # ### end Alembic commands ###
